name: Build & Release
on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
        #   flutter-version: 3.1.1
        #   flutter-version-file: pubspec.yaml
          
      - name: Verify Flutter Installation
        run: flutter --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/releasekey.jks
          ls -al android/app

      - name: Create Keystore.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=releasekey.jks" >> android/key.properties
          cat android/key.properties

      - name: Build android App
        run: flutter build apk --release

      - name: Push APK to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*.apk"
          token: ${{ secrets.TOKEN}}

    #   - name: Upload iOS App Artifacts
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: ios-config
    #       path: ios-config.zip

    #   - name: Upload IPA Artifacts
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: ios-app
    #       path: ios-app.zip
